services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - SQLITE_PATH=/data/pgallbattle.db
    volumes:
      - /data/APP-DATA/pgallBattle/data:/data:Z
      - /data/APP-DATA/pgallBattle/logs:/app/logs:Z
    ports:
      - "8280:8080"

  web:
    build: ./web
    ports:
      - "82:80"
    depends_on:
      - api